### ISSUE TITLE
Types containing naked type parameters as elements in a base class incorrectly fail discovery

### ISSUE THREAD

**Issue by davkean** [microsoft/vs-mef#180]
Given the following:

``` C# 
    internal interface IActiveConfiguredValues<T>
    {
    }

    internal abstract class AbstractActiveConfiguredValue<T> 
    {
    }

    [Export(typeof(IActiveConfiguredValues<>))]
    internal class ActiveConfiguredValues<T> : AbstractActiveConfiguredValue<IEnumerable<T>>,  IActiveConfiguredValues<T>
    {
    }
```

During discovery I get:

```
Microsoft.VisualStudio.Composition.PartDiscoveryException: Failure while scanning type "Microsoft.VisualStudio.ProjectSystem.ActiveConfiguredValues`1". ---> System.ArgumentException: Generic parameters are not supported.
Parameter name: type
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef..ctor(Resolver resolver, Type type, Boolean shallow)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.<>c__DisplayClass9_0.<.ctor>b__1(Type t)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef..ctor(Resolver resolver, Type type, Boolean shallow)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.Get(Type type, Resolver resolver)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef..ctor(Resolver resolver, Type type, Boolean shallow)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.<>c__DisplayClass9_0.<.ctor>b__1(Type t)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef..ctor(Resolver resolver, Type type, Boolean shallow)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.<>c__DisplayClass9_0.<.ctor>b__2(Type t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef..ctor(Resolver resolver, Type type, Boolean shallow)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.Get(Type type, Resolver resolver)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscoveryV1.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.CombinedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.<>c__DisplayClass31_0.<CreateDiscoveryBlockChain>b__0(Type type)
   --- End of inner exception stack trace ---
```

Changing the definition to:

``` C#
    [Export(typeof(IActiveConfiguredValues<>))]
    internal class ActiveConfiguredValues<T> : AbstractActiveConfiguredValue<T>,  IActiveConfiguredValues<T>
    {
    }
```

-or-

``` C#
    [Export(typeof(IActiveConfiguredValues<>))]
    internal class ActiveConfiguredValues<T> : AbstractActiveConfiguredValue<object>,  IActiveConfiguredValues<T>
    {
    }
```

Works as expected. VS MEF shouldn't care about this the element type of the argument to AbstractActiveConfiguredValue<T> it's an implementation detail of the part and not part of any contract, import or export.

**Comment by AArnott** [comment]
It's a by design limitation that you couldn't *import* `T`, but as you point out, you're not doing that.
I suspect this is simply a code limitation due to how we store `TypeRef`'s that support lazy loaded assemblies. I hope and expect we can find a solution to this.

**Comment by davkean** [comment]
Note it appears to be only when T is an element of a collection type.
