### ISSUE TITLE
Error when encountering a null ImportMany "collection" should be a little more obvious

### ISSUE THREAD

**Issue by davkean** [Microsoft/vs-mef#68]
Had the following code:

```
        public UnconfiguredProjectContextProvider()
        {
        }

        [ImportMany]
        public OrderPrecedenceImportCollection<IProjectGuidService> ProjectGuidServices
        {
            get;
        }
```

Notice I hadn't instantiated the collection above, and got the following:

```
Microsoft.VisualStudio.Composition.CompositionFailedException: Import "Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectContextProvider.ProjectGuidServices" could not be satisfied. ---> Microsoft.VisualStudio.Composition.CompositionFailedException: Unable to instantiate custom import collection type.
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.SatisfyImmediateImports()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()

```

It would be helpful to provide a little more info here - you can't instantiate a new version of the collection here, but that's not the problem in this case - we forgot to instantiate it.

**Comment by AArnott** [comment]
@davkean MEF can instantiate some concrete collection types that follow certain patterns. This one doesn't. It's letting you know that. I'm not sure how to improve on that. What if we added a sentence at the end of the inner-most exception's message: "Did you forget to instantiate it in your importing constructor?" Would that help?

**Comment by AArnott** [comment]
never mind. I've got an idea of how to make this better.
